// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class DocumentationResponse {
  static encode(message: DocumentationResponse, writer: Writer): void {
    const pages = message.pages;
    if (pages.length !== 0) {
      for (let i: i32 = 0; i < pages.length; ++i) {
        writer.uint32(10);
        writer.bytes(pages[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): DocumentationResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DocumentationResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.pages.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  pages: Array<Uint8Array>;

  constructor(pages: Array<Uint8Array> = []) {
    this.pages = pages;
  }
}
