// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class Quantity {
  static encode(message: Quantity, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.string);
  }

  static decode(reader: Reader, length: i32): Quantity {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Quantity();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.string = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  string: string;

  constructor(string: string = "") {
    this.string = string;
  }
}
