apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8091
metrics:
  bindAddress: 127.0.0.1:8090
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 0ff08fbf.suffiks.com
