apiVersion: suffiks.com/v1
kind: ProjectConfig
health:
  healthProbeBindAddress: :8091
metrics:
  bindAddress: 127.0.0.1:8090
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 0ff08fbf.suffiks.com
