// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class TableOptions {
  static encode(message: TableOptions, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.includeObject);
  }

  static decode(reader: Reader, length: i32): TableOptions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TableOptions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.includeObject = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  includeObject: string;

  constructor(includeObject: string = "") {
    this.includeObject = includeObject;
  }
}
