// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class TypeMeta {
  static encode(message: TypeMeta, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.kind);

    writer.uint32(18);
    writer.string(message.apiVersion);
  }

  static decode(reader: Reader, length: i32): TypeMeta {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TypeMeta();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.kind = reader.string();
          break;

        case 2:
          message.apiVersion = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  kind: string;
  apiVersion: string;

  constructor(kind: string = "", apiVersion: string = "") {
    this.kind = kind;
    this.apiVersion = apiVersion;
  }
}
