---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-suffiks-com-v1-extension
  failurePolicy: Fail
  name: vextension.kb.io
  rules:
  - apiGroups:
    - suffiks.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - extensions
  sideEffects: None
