---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{.Name }}"-extension
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{.Name }}"-extension
subjects:
  - kind: ServiceAccount
    name: "{{.Name }}"
    namespace: system
