// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { APIResource } from "./APIResource";

export class APIResourceList {
  static encode(message: APIResourceList, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.groupVersion);

    const resources = message.resources;
    for (let i: i32 = 0; i < resources.length; ++i) {
      writer.uint32(18);
      writer.fork();
      APIResource.encode(resources[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): APIResourceList {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new APIResourceList();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.groupVersion = reader.string();
          break;

        case 2:
          message.resources.push(APIResource.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  groupVersion: string;
  resources: Array<APIResource>;

  constructor(groupVersion: string = "", resources: Array<APIResource> = []) {
    this.groupVersion = groupVersion;
    this.resources = resources;
  }
}
