// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class FieldsV1 {
  static encode(message: FieldsV1, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.raw);
  }

  static decode(reader: Reader, length: i32): FieldsV1 {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new FieldsV1();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.raw = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  raw: Uint8Array;

  constructor(raw: Uint8Array = new Uint8Array(0)) {
    this.raw = raw;
  }
}
