// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class GroupVersionKind {
  static encode(message: GroupVersionKind, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.group);

    writer.uint32(18);
    writer.string(message.version);

    writer.uint32(26);
    writer.string(message.kind);
  }

  static decode(reader: Reader, length: i32): GroupVersionKind {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GroupVersionKind();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.group = reader.string();
          break;

        case 2:
          message.version = reader.string();
          break;

        case 3:
          message.kind = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  group: string;
  version: string;
  kind: string;

  constructor(group: string = "", version: string = "", kind: string = "") {
    this.group = group;
    this.version = version;
    this.kind = kind;
  }
}
