// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectMeta } from "./ObjectMeta";

export class PartialObjectMetadata {
  static encode(message: PartialObjectMetadata, writer: Writer): void {
    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectMeta.encode(metadata, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PartialObjectMetadata {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PartialObjectMetadata();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metadata: ObjectMeta | null;

  constructor(metadata: ObjectMeta | null = null) {
    this.metadata = metadata;
  }
}
