// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class StatusCause {
  static encode(message: StatusCause, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.reason);

    writer.uint32(18);
    writer.string(message.message);

    writer.uint32(26);
    writer.string(message.field);
  }

  static decode(reader: Reader, length: i32): StatusCause {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StatusCause();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.reason = reader.string();
          break;

        case 2:
          message.message = reader.string();
          break;

        case 3:
          message.field = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  reason: string;
  message: string;
  field: string;

  constructor(reason: string = "", message: string = "", field: string = "") {
    this.reason = reason;
    this.message = message;
    this.field = field;
  }
}
