// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { RawExtension } from "../../../runtime/RawExtension";

export class WatchEvent {
  static encode(message: WatchEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.type);

    const object = message.object;
    if (object !== null) {
      writer.uint32(18);
      writer.fork();
      RawExtension.encode(object, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): WatchEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new WatchEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.type = reader.string();
          break;

        case 2:
          message.object = RawExtension.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  type: string;
  object: RawExtension | null;

  constructor(type: string = "", object: RawExtension | null = null) {
    this.type = type;
    this.object = object;
  }
}
