# permissions for end users to view extensions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extension-viewer-role
rules:
  - apiGroups:
      - suffiks.com
    resources:
      - extensions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - suffiks.com
    resources:
      - extensions/status
    verbs:
      - get
