// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class AttachedVolume {
  static encode(message: AttachedVolume, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(18);
    writer.string(message.devicePath);
  }

  static decode(reader: Reader, length: i32): AttachedVolume {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AttachedVolume();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.devicePath = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  devicePath: string;

  constructor(name: string = "", devicePath: string = "") {
    this.name = name;
    this.devicePath = devicePath;
  }
}
