// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class AzureFilePersistentVolumeSource {
  static encode(
    message: AzureFilePersistentVolumeSource,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.secretName);

    writer.uint32(18);
    writer.string(message.shareName);

    writer.uint32(24);
    writer.bool(message.readOnly);

    writer.uint32(34);
    writer.string(message.secretNamespace);
  }

  static decode(reader: Reader, length: i32): AzureFilePersistentVolumeSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AzureFilePersistentVolumeSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.secretName = reader.string();
          break;

        case 2:
          message.shareName = reader.string();
          break;

        case 3:
          message.readOnly = reader.bool();
          break;

        case 4:
          message.secretNamespace = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  secretName: string;
  shareName: string;
  readOnly: bool;
  secretNamespace: string;

  constructor(
    secretName: string = "",
    shareName: string = "",
    readOnly: bool = false,
    secretNamespace: string = ""
  ) {
    this.secretName = secretName;
    this.shareName = shareName;
    this.readOnly = readOnly;
    this.secretNamespace = secretNamespace;
  }
}
