// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class ComponentCondition {
  static encode(message: ComponentCondition, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.type);

    writer.uint32(18);
    writer.string(message.status);

    writer.uint32(26);
    writer.string(message.message);

    writer.uint32(34);
    writer.string(message.error);
  }

  static decode(reader: Reader, length: i32): ComponentCondition {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComponentCondition();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.type = reader.string();
          break;

        case 2:
          message.status = reader.string();
          break;

        case 3:
          message.message = reader.string();
          break;

        case 4:
          message.error = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  type: string;
  status: string;
  message: string;
  error: string;

  constructor(
    type: string = "",
    status: string = "",
    message: string = "",
    error: string = ""
  ) {
    this.type = type;
    this.status = status;
    this.message = message;
    this.error = error;
  }
}
