// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectMeta } from "../../../apimachinery/pkg/apis/meta/v1/ObjectMeta";
import { ComponentCondition } from "./ComponentCondition";

export class ComponentStatus {
  static encode(message: ComponentStatus, writer: Writer): void {
    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectMeta.encode(metadata, writer);
      writer.ldelim();
    }

    const conditions = message.conditions;
    for (let i: i32 = 0; i < conditions.length; ++i) {
      writer.uint32(18);
      writer.fork();
      ComponentCondition.encode(conditions[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ComponentStatus {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComponentStatus();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          break;

        case 2:
          message.conditions.push(
            ComponentCondition.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metadata: ObjectMeta | null;
  conditions: Array<ComponentCondition>;

  constructor(
    metadata: ObjectMeta | null = null,
    conditions: Array<ComponentCondition> = []
  ) {
    this.metadata = metadata;
    this.conditions = conditions;
  }
}
