// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class ConfigMapNodeConfigSource {
  static encode(message: ConfigMapNodeConfigSource, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.namespace);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.uid);

    writer.uint32(34);
    writer.string(message.resourceVersion);

    writer.uint32(42);
    writer.string(message.kubeletConfigKey);
  }

  static decode(reader: Reader, length: i32): ConfigMapNodeConfigSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ConfigMapNodeConfigSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.namespace = reader.string();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.uid = reader.string();
          break;

        case 4:
          message.resourceVersion = reader.string();
          break;

        case 5:
          message.kubeletConfigKey = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  namespace: string;
  name: string;
  uid: string;
  resourceVersion: string;
  kubeletConfigKey: string;

  constructor(
    namespace: string = "",
    name: string = "",
    uid: string = "",
    resourceVersion: string = "",
    kubeletConfigKey: string = ""
  ) {
    this.namespace = namespace;
    this.name = name;
    this.uid = uid;
    this.resourceVersion = resourceVersion;
    this.kubeletConfigKey = kubeletConfigKey;
  }
}
