// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { Time } from "../../../apimachinery/pkg/apis/meta/v1/Time";

export class ContainerStateRunning {
  static encode(message: ContainerStateRunning, writer: Writer): void {
    const startedAt = message.startedAt;
    if (startedAt !== null) {
      writer.uint32(10);
      writer.fork();
      Time.encode(startedAt, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ContainerStateRunning {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ContainerStateRunning();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.startedAt = Time.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  startedAt: Time | null;

  constructor(startedAt: Time | null = null) {
    this.startedAt = startedAt;
  }
}
