// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectMeta } from "../../../apimachinery/pkg/apis/meta/v1/ObjectMeta";
import { EndpointSubset } from "./EndpointSubset";

export class Endpoints {
  static encode(message: Endpoints, writer: Writer): void {
    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectMeta.encode(metadata, writer);
      writer.ldelim();
    }

    const subsets = message.subsets;
    for (let i: i32 = 0; i < subsets.length; ++i) {
      writer.uint32(18);
      writer.fork();
      EndpointSubset.encode(subsets[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Endpoints {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Endpoints();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          break;

        case 2:
          message.subsets.push(EndpointSubset.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metadata: ObjectMeta | null;
  subsets: Array<EndpointSubset>;

  constructor(
    metadata: ObjectMeta | null = null,
    subsets: Array<EndpointSubset> = []
  ) {
    this.metadata = metadata;
    this.subsets = subsets;
  }
}
