// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class EndpointPort {
  static encode(message: EndpointPort, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(16);
    writer.int32(message.port);

    writer.uint32(26);
    writer.string(message.protocol);

    writer.uint32(34);
    writer.string(message.appProtocol);
  }

  static decode(reader: Reader, length: i32): EndpointPort {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EndpointPort();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.port = reader.int32();
          break;

        case 3:
          message.protocol = reader.string();
          break;

        case 4:
          message.appProtocol = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  port: i32;
  protocol: string;
  appProtocol: string;

  constructor(
    name: string = "",
    port: i32 = 0,
    protocol: string = "",
    appProtocol: string = ""
  ) {
    this.name = name;
    this.port = port;
    this.protocol = protocol;
    this.appProtocol = appProtocol;
  }
}
