// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { MicroTime } from "../../../apimachinery/pkg/apis/meta/v1/MicroTime";

export class EventSeries {
  static encode(message: EventSeries, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.count);

    const lastObservedTime = message.lastObservedTime;
    if (lastObservedTime !== null) {
      writer.uint32(18);
      writer.fork();
      MicroTime.encode(lastObservedTime, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): EventSeries {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EventSeries();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.count = reader.int32();
          break;

        case 2:
          message.lastObservedTime = MicroTime.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  count: i32;
  lastObservedTime: MicroTime | null;

  constructor(count: i32 = 0, lastObservedTime: MicroTime | null = null) {
    this.count = count;
    this.lastObservedTime = lastObservedTime;
  }
}
