// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class ExecAction {
  static encode(message: ExecAction, writer: Writer): void {
    const command = message.command;
    if (command.length !== 0) {
      for (let i: i32 = 0; i < command.length; ++i) {
        writer.uint32(10);
        writer.string(command[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): ExecAction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ExecAction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.command.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  command: Array<string>;

  constructor(command: Array<string> = []) {
    this.command = command;
  }
}
