// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class GitRepoVolumeSource {
  static encode(message: GitRepoVolumeSource, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.repository);

    writer.uint32(18);
    writer.string(message.revision);

    writer.uint32(26);
    writer.string(message.directory);
  }

  static decode(reader: Reader, length: i32): GitRepoVolumeSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GitRepoVolumeSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.repository = reader.string();
          break;

        case 2:
          message.revision = reader.string();
          break;

        case 3:
          message.directory = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  repository: string;
  revision: string;
  directory: string;

  constructor(
    repository: string = "",
    revision: string = "",
    directory: string = ""
  ) {
    this.repository = repository;
    this.revision = revision;
    this.directory = directory;
  }
}
