// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class GlusterfsPersistentVolumeSource {
  static encode(
    message: GlusterfsPersistentVolumeSource,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.endpoints);

    writer.uint32(18);
    writer.string(message.path);

    writer.uint32(24);
    writer.bool(message.readOnly);

    writer.uint32(34);
    writer.string(message.endpointsNamespace);
  }

  static decode(reader: Reader, length: i32): GlusterfsPersistentVolumeSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GlusterfsPersistentVolumeSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.endpoints = reader.string();
          break;

        case 2:
          message.path = reader.string();
          break;

        case 3:
          message.readOnly = reader.bool();
          break;

        case 4:
          message.endpointsNamespace = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  endpoints: string;
  path: string;
  readOnly: bool;
  endpointsNamespace: string;

  constructor(
    endpoints: string = "",
    path: string = "",
    readOnly: bool = false,
    endpointsNamespace: string = ""
  ) {
    this.endpoints = endpoints;
    this.path = path;
    this.readOnly = readOnly;
    this.endpointsNamespace = endpointsNamespace;
  }
}
