// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class HostAlias {
  static encode(message: HostAlias, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.ip);

    const hostnames = message.hostnames;
    if (hostnames.length !== 0) {
      for (let i: i32 = 0; i < hostnames.length; ++i) {
        writer.uint32(18);
        writer.string(hostnames[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): HostAlias {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new HostAlias();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.ip = reader.string();
          break;

        case 2:
          message.hostnames.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  ip: string;
  hostnames: Array<string>;

  constructor(ip: string = "", hostnames: Array<string> = []) {
    this.ip = ip;
    this.hostnames = hostnames;
  }
}
