// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { LimitRangeItem } from "./LimitRangeItem";

export class LimitRangeSpec {
  static encode(message: LimitRangeSpec, writer: Writer): void {
    const limits = message.limits;
    for (let i: i32 = 0; i < limits.length; ++i) {
      writer.uint32(10);
      writer.fork();
      LimitRangeItem.encode(limits[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): LimitRangeSpec {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new LimitRangeSpec();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.limits.push(LimitRangeItem.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  limits: Array<LimitRangeItem>;

  constructor(limits: Array<LimitRangeItem> = []) {
    this.limits = limits;
  }
}
