// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { NodeSelector } from "./NodeSelector";
import { PreferredSchedulingTerm } from "./PreferredSchedulingTerm";

export class NodeAffinity {
  static encode(message: NodeAffinity, writer: Writer): void {
    const requiredDuringSchedulingIgnoredDuringExecution =
      message.requiredDuringSchedulingIgnoredDuringExecution;
    if (requiredDuringSchedulingIgnoredDuringExecution !== null) {
      writer.uint32(10);
      writer.fork();
      NodeSelector.encode(
        requiredDuringSchedulingIgnoredDuringExecution,
        writer
      );
      writer.ldelim();
    }

    const preferredDuringSchedulingIgnoredDuringExecution =
      message.preferredDuringSchedulingIgnoredDuringExecution;
    for (
      let i: i32 = 0;
      i < preferredDuringSchedulingIgnoredDuringExecution.length;
      ++i
    ) {
      writer.uint32(18);
      writer.fork();
      PreferredSchedulingTerm.encode(
        preferredDuringSchedulingIgnoredDuringExecution[i],
        writer
      );
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): NodeAffinity {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NodeAffinity();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.requiredDuringSchedulingIgnoredDuringExecution =
            NodeSelector.decode(reader, reader.uint32());
          break;

        case 2:
          message.preferredDuringSchedulingIgnoredDuringExecution.push(
            PreferredSchedulingTerm.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  requiredDuringSchedulingIgnoredDuringExecution: NodeSelector | null;
  preferredDuringSchedulingIgnoredDuringExecution: Array<PreferredSchedulingTerm>;

  constructor(
    requiredDuringSchedulingIgnoredDuringExecution: NodeSelector | null = null,
    preferredDuringSchedulingIgnoredDuringExecution: Array<PreferredSchedulingTerm> = []
  ) {
    this.requiredDuringSchedulingIgnoredDuringExecution =
      requiredDuringSchedulingIgnoredDuringExecution;
    this.preferredDuringSchedulingIgnoredDuringExecution =
      preferredDuringSchedulingIgnoredDuringExecution;
  }
}
