// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { DaemonEndpoint } from "./DaemonEndpoint";

export class NodeDaemonEndpoints {
  static encode(message: NodeDaemonEndpoints, writer: Writer): void {
    const kubeletEndpoint = message.kubeletEndpoint;
    if (kubeletEndpoint !== null) {
      writer.uint32(10);
      writer.fork();
      DaemonEndpoint.encode(kubeletEndpoint, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): NodeDaemonEndpoints {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NodeDaemonEndpoints();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.kubeletEndpoint = DaemonEndpoint.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  kubeletEndpoint: DaemonEndpoint | null;

  constructor(kubeletEndpoint: DaemonEndpoint | null = null) {
    this.kubeletEndpoint = kubeletEndpoint;
  }
}
