// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { NodeSelectorRequirement } from "./NodeSelectorRequirement";

export class NodeSelectorTerm {
  static encode(message: NodeSelectorTerm, writer: Writer): void {
    const matchExpressions = message.matchExpressions;
    for (let i: i32 = 0; i < matchExpressions.length; ++i) {
      writer.uint32(10);
      writer.fork();
      NodeSelectorRequirement.encode(matchExpressions[i], writer);
      writer.ldelim();
    }

    const matchFields = message.matchFields;
    for (let i: i32 = 0; i < matchFields.length; ++i) {
      writer.uint32(18);
      writer.fork();
      NodeSelectorRequirement.encode(matchFields[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): NodeSelectorTerm {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NodeSelectorTerm();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.matchExpressions.push(
            NodeSelectorRequirement.decode(reader, reader.uint32())
          );
          break;

        case 2:
          message.matchFields.push(
            NodeSelectorRequirement.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  matchExpressions: Array<NodeSelectorRequirement>;
  matchFields: Array<NodeSelectorRequirement>;

  constructor(
    matchExpressions: Array<NodeSelectorRequirement> = [],
    matchFields: Array<NodeSelectorRequirement> = []
  ) {
    this.matchExpressions = matchExpressions;
    this.matchFields = matchFields;
  }
}
