// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class ObjectReference {
  static encode(message: ObjectReference, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.kind);

    writer.uint32(18);
    writer.string(message.namespace);

    writer.uint32(26);
    writer.string(message.name);

    writer.uint32(34);
    writer.string(message.uid);

    writer.uint32(42);
    writer.string(message.apiVersion);

    writer.uint32(50);
    writer.string(message.resourceVersion);

    writer.uint32(58);
    writer.string(message.fieldPath);
  }

  static decode(reader: Reader, length: i32): ObjectReference {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ObjectReference();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.kind = reader.string();
          break;

        case 2:
          message.namespace = reader.string();
          break;

        case 3:
          message.name = reader.string();
          break;

        case 4:
          message.uid = reader.string();
          break;

        case 5:
          message.apiVersion = reader.string();
          break;

        case 6:
          message.resourceVersion = reader.string();
          break;

        case 7:
          message.fieldPath = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  kind: string;
  namespace: string;
  name: string;
  uid: string;
  apiVersion: string;
  resourceVersion: string;
  fieldPath: string;

  constructor(
    kind: string = "",
    namespace: string = "",
    name: string = "",
    uid: string = "",
    apiVersion: string = "",
    resourceVersion: string = "",
    fieldPath: string = ""
  ) {
    this.kind = kind;
    this.namespace = namespace;
    this.name = name;
    this.uid = uid;
    this.apiVersion = apiVersion;
    this.resourceVersion = resourceVersion;
    this.fieldPath = fieldPath;
  }
}
