// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { LabelSelector } from "../../../apimachinery/pkg/apis/meta/v1/LabelSelector";

export class PodAffinityTerm {
  static encode(message: PodAffinityTerm, writer: Writer): void {
    const labelSelector = message.labelSelector;
    if (labelSelector !== null) {
      writer.uint32(10);
      writer.fork();
      LabelSelector.encode(labelSelector, writer);
      writer.ldelim();
    }

    const namespaces = message.namespaces;
    if (namespaces.length !== 0) {
      for (let i: i32 = 0; i < namespaces.length; ++i) {
        writer.uint32(18);
        writer.string(namespaces[i]);
      }
    }

    writer.uint32(26);
    writer.string(message.topologyKey);

    const namespaceSelector = message.namespaceSelector;
    if (namespaceSelector !== null) {
      writer.uint32(34);
      writer.fork();
      LabelSelector.encode(namespaceSelector, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PodAffinityTerm {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PodAffinityTerm();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.labelSelector = LabelSelector.decode(reader, reader.uint32());
          break;

        case 2:
          message.namespaces.push(reader.string());
          break;

        case 3:
          message.topologyKey = reader.string();
          break;

        case 4:
          message.namespaceSelector = LabelSelector.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  labelSelector: LabelSelector | null;
  namespaces: Array<string>;
  topologyKey: string;
  namespaceSelector: LabelSelector | null;

  constructor(
    labelSelector: LabelSelector | null = null,
    namespaces: Array<string> = [],
    topologyKey: string = "",
    namespaceSelector: LabelSelector | null = null
  ) {
    this.labelSelector = labelSelector;
    this.namespaces = namespaces;
    this.topologyKey = topologyKey;
    this.namespaceSelector = namespaceSelector;
  }
}
