// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { SELinuxOptions } from "./SELinuxOptions";
import { WindowsSecurityContextOptions } from "./WindowsSecurityContextOptions";
import { Sysctl } from "./Sysctl";
import { SeccompProfile } from "./SeccompProfile";

export class PodSecurityContext {
  static encode(message: PodSecurityContext, writer: Writer): void {
    const seLinuxOptions = message.seLinuxOptions;
    if (seLinuxOptions !== null) {
      writer.uint32(10);
      writer.fork();
      SELinuxOptions.encode(seLinuxOptions, writer);
      writer.ldelim();
    }

    const windowsOptions = message.windowsOptions;
    if (windowsOptions !== null) {
      writer.uint32(66);
      writer.fork();
      WindowsSecurityContextOptions.encode(windowsOptions, writer);
      writer.ldelim();
    }

    writer.uint32(16);
    writer.int64(message.runAsUser);

    writer.uint32(48);
    writer.int64(message.runAsGroup);

    writer.uint32(24);
    writer.bool(message.runAsNonRoot);

    const supplementalGroups = message.supplementalGroups;
    if (supplementalGroups.length !== 0) {
      for (let i: i32 = 0; i < supplementalGroups.length; ++i) {
        writer.uint32(32);
        writer.int64(supplementalGroups[i]);
      }
    }

    writer.uint32(40);
    writer.int64(message.fsGroup);

    const sysctls = message.sysctls;
    for (let i: i32 = 0; i < sysctls.length; ++i) {
      writer.uint32(58);
      writer.fork();
      Sysctl.encode(sysctls[i], writer);
      writer.ldelim();
    }

    writer.uint32(74);
    writer.string(message.fsGroupChangePolicy);

    const seccompProfile = message.seccompProfile;
    if (seccompProfile !== null) {
      writer.uint32(82);
      writer.fork();
      SeccompProfile.encode(seccompProfile, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PodSecurityContext {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PodSecurityContext();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.seLinuxOptions = SELinuxOptions.decode(
            reader,
            reader.uint32()
          );
          break;

        case 8:
          message.windowsOptions = WindowsSecurityContextOptions.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.runAsUser = reader.int64();
          break;

        case 6:
          message.runAsGroup = reader.int64();
          break;

        case 3:
          message.runAsNonRoot = reader.bool();
          break;

        case 4:
          message.supplementalGroups.push(reader.int64());
          break;

        case 5:
          message.fsGroup = reader.int64();
          break;

        case 7:
          message.sysctls.push(Sysctl.decode(reader, reader.uint32()));
          break;

        case 9:
          message.fsGroupChangePolicy = reader.string();
          break;

        case 10:
          message.seccompProfile = SeccompProfile.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  seLinuxOptions: SELinuxOptions | null;
  windowsOptions: WindowsSecurityContextOptions | null;
  runAsUser: i64;
  runAsGroup: i64;
  runAsNonRoot: bool;
  supplementalGroups: Array<i64>;
  fsGroup: i64;
  sysctls: Array<Sysctl>;
  fsGroupChangePolicy: string;
  seccompProfile: SeccompProfile | null;

  constructor(
    seLinuxOptions: SELinuxOptions | null = null,
    windowsOptions: WindowsSecurityContextOptions | null = null,
    runAsUser: i64 = 0,
    runAsGroup: i64 = 0,
    runAsNonRoot: bool = false,
    supplementalGroups: Array<i64> = [],
    fsGroup: i64 = 0,
    sysctls: Array<Sysctl> = [],
    fsGroupChangePolicy: string = "",
    seccompProfile: SeccompProfile | null = null
  ) {
    this.seLinuxOptions = seLinuxOptions;
    this.windowsOptions = windowsOptions;
    this.runAsUser = runAsUser;
    this.runAsGroup = runAsGroup;
    this.runAsNonRoot = runAsNonRoot;
    this.supplementalGroups = supplementalGroups;
    this.fsGroup = fsGroup;
    this.sysctls = sysctls;
    this.fsGroupChangePolicy = fsGroupChangePolicy;
    this.seccompProfile = seccompProfile;
  }
}
