// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class SELinuxOptions {
  static encode(message: SELinuxOptions, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.user);

    writer.uint32(18);
    writer.string(message.role);

    writer.uint32(26);
    writer.string(message.type);

    writer.uint32(34);
    writer.string(message.level);
  }

  static decode(reader: Reader, length: i32): SELinuxOptions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SELinuxOptions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.user = reader.string();
          break;

        case 2:
          message.role = reader.string();
          break;

        case 3:
          message.type = reader.string();
          break;

        case 4:
          message.level = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  user: string;
  role: string;
  type: string;
  level: string;

  constructor(
    user: string = "",
    role: string = "",
    type: string = "",
    level: string = ""
  ) {
    this.user = user;
    this.role = role;
    this.type = type;
    this.level = level;
  }
}
