// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectReference } from "./ObjectReference";

export class SerializedReference {
  static encode(message: SerializedReference, writer: Writer): void {
    const reference = message.reference;
    if (reference !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectReference.encode(reference, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SerializedReference {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SerializedReference();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.reference = ObjectReference.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  reference: ObjectReference | null;

  constructor(reference: ObjectReference | null = null) {
    this.reference = reference;
  }
}
