// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { NodeSelector } from "./NodeSelector";

export class VolumeNodeAffinity {
  static encode(message: VolumeNodeAffinity, writer: Writer): void {
    const required = message.required;
    if (required !== null) {
      writer.uint32(10);
      writer.fork();
      NodeSelector.encode(required, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): VolumeNodeAffinity {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VolumeNodeAffinity();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.required = NodeSelector.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  required: NodeSelector | null;

  constructor(required: NodeSelector | null = null) {
    this.required = required;
  }
}
