apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "suffiks.fullname" . }}-manager-role
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - suffiks.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - suffiks.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - suffiks.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - suffiks.com
  resources:
  - extensions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - suffiks.com
  resources:
  - extensions/finalizers
  verbs:
  - update
- apiGroups:
  - suffiks.com
  resources:
  - extensions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - suffiks.com
  resources:
  - works
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - suffiks.com
  resources:
  - works/finalizers
  verbs:
  - update
- apiGroups:
  - suffiks.com
  resources:
  - works/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "suffiks.fullname" . }}-manager-rolebinding
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "suffiks.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "suffiks.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'