apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "suffiks.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "suffiks.fullname" . }}-serving-cert
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "suffiks.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-suffiks-com-v1-application
  failurePolicy: Fail
  name: mapplication.kb.io
  rules:
  - apiGroups:
    - suffiks.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "suffiks.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-suffiks-com-v1-work
  failurePolicy: Fail
  name: mwork.kb.io
  rules:
  - apiGroups:
    - suffiks.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - works
  sideEffects: None