apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "suffiks.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "suffiks.fullname" . }}-serving-cert
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "suffiks.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-suffiks-com-v1-extension
  failurePolicy: Fail
  name: vextension.kb.io
  rules:
  - apiGroups:
    - suffiks.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - extensions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "suffiks.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-suffiks-com-v1-application
  failurePolicy: Fail
  name: vapplication.kb.io
  rules:
  - apiGroups:
    - suffiks.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "suffiks.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-suffiks-com-v1-work
  failurePolicy: Fail
  name: vwork.kb.io
  rules:
  - apiGroups:
    - suffiks.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - works
  sideEffects: None