apiVersion: suffiks.com/v1
kind: Extension
metadata:
  name: extension-sample
spec:
  targets:
    - Application
  controller:
    service: suffiks-ingress
    namespace: system
  openAPIV3Schema:
    type: object
    properties:
      spec:
        properties:
          ingresses:
            description:
              List of URLs that will route HTTPS traffic to the application.
              All URLs must start with `https://`. Domain availability differs
              according to which environment your application is running in.
            items:
              pattern: ^https:\/\/.+$
              type: string
            type: array
        type: object
