// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/suffiks/suffiks/pkg/client/clientset_generated/versioned/typed/suffiks/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSuffiksV1 struct {
	*testing.Fake
}

func (c *FakeSuffiksV1) Applications(namespace string) v1.ApplicationInterface {
	return &FakeApplications{c, namespace}
}

func (c *FakeSuffiksV1) Extensions(namespace string) v1.ExtensionInterface {
	return &FakeExtensions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSuffiksV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
