// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ValidationError } from "./ValidationError";

export class ValidationResponse {
  static encode(message: ValidationResponse, writer: Writer): void {
    const errors = message.errors;
    for (let i: i32 = 0; i < errors.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ValidationError.encode(errors[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ValidationResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ValidationResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.errors.push(ValidationError.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  errors: Array<ValidationError>;

  constructor(errors: Array<ValidationError> = []) {
    this.errors = errors;
  }
}
