// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { PreferAvoidPodsEntry } from "./PreferAvoidPodsEntry";

export class AvoidPods {
  static encode(message: AvoidPods, writer: Writer): void {
    const preferAvoidPods = message.preferAvoidPods;
    for (let i: i32 = 0; i < preferAvoidPods.length; ++i) {
      writer.uint32(10);
      writer.fork();
      PreferAvoidPodsEntry.encode(preferAvoidPods[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): AvoidPods {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AvoidPods();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.preferAvoidPods.push(
            PreferAvoidPodsEntry.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  preferAvoidPods: Array<PreferAvoidPodsEntry>;

  constructor(preferAvoidPods: Array<PreferAvoidPodsEntry> = []) {
    this.preferAvoidPods = preferAvoidPods;
  }
}
