// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { LocalObjectReference } from "./LocalObjectReference";
import { KeyToPath } from "./KeyToPath";

export class ConfigMapVolumeSource {
  static encode(message: ConfigMapVolumeSource, writer: Writer): void {
    const localObjectReference = message.localObjectReference;
    if (localObjectReference !== null) {
      writer.uint32(10);
      writer.fork();
      LocalObjectReference.encode(localObjectReference, writer);
      writer.ldelim();
    }

    const items = message.items;
    for (let i: i32 = 0; i < items.length; ++i) {
      writer.uint32(18);
      writer.fork();
      KeyToPath.encode(items[i], writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.int32(message.defaultMode);

    writer.uint32(32);
    writer.bool(message.optional);
  }

  static decode(reader: Reader, length: i32): ConfigMapVolumeSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ConfigMapVolumeSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.localObjectReference = LocalObjectReference.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.items.push(KeyToPath.decode(reader, reader.uint32()));
          break;

        case 3:
          message.defaultMode = reader.int32();
          break;

        case 4:
          message.optional = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  localObjectReference: LocalObjectReference | null;
  items: Array<KeyToPath>;
  defaultMode: i32;
  optional: bool;

  constructor(
    localObjectReference: LocalObjectReference | null = null,
    items: Array<KeyToPath> = [],
    defaultMode: i32 = 0,
    optional: bool = false
  ) {
    this.localObjectReference = localObjectReference;
    this.items = items;
    this.defaultMode = defaultMode;
    this.optional = optional;
  }
}
