// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { Quantity } from "../../../apimachinery/pkg/api/resource/Quantity";

export class EmptyDirVolumeSource {
  static encode(message: EmptyDirVolumeSource, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.medium);

    const sizeLimit = message.sizeLimit;
    if (sizeLimit !== null) {
      writer.uint32(18);
      writer.fork();
      Quantity.encode(sizeLimit, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): EmptyDirVolumeSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EmptyDirVolumeSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.medium = reader.string();
          break;

        case 2:
          message.sizeLimit = Quantity.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  medium: string;
  sizeLimit: Quantity | null;

  constructor(medium: string = "", sizeLimit: Quantity | null = null) {
    this.medium = medium;
    this.sizeLimit = sizeLimit;
  }
}
