// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { PersistentVolumeClaimTemplate } from "./PersistentVolumeClaimTemplate";

export class EphemeralVolumeSource {
  static encode(message: EphemeralVolumeSource, writer: Writer): void {
    const volumeClaimTemplate = message.volumeClaimTemplate;
    if (volumeClaimTemplate !== null) {
      writer.uint32(10);
      writer.fork();
      PersistentVolumeClaimTemplate.encode(volumeClaimTemplate, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): EphemeralVolumeSource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EphemeralVolumeSource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.volumeClaimTemplate = PersistentVolumeClaimTemplate.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  volumeClaimTemplate: PersistentVolumeClaimTemplate | null;

  constructor(
    volumeClaimTemplate: PersistentVolumeClaimTemplate | null = null
  ) {
    this.volumeClaimTemplate = volumeClaimTemplate;
  }
}
