// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectMeta } from "../../../apimachinery/pkg/apis/meta/v1/ObjectMeta";
import { PersistentVolumeSpec } from "./PersistentVolumeSpec";
import { PersistentVolumeStatus } from "./PersistentVolumeStatus";

export class PersistentVolume {
  static encode(message: PersistentVolume, writer: Writer): void {
    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectMeta.encode(metadata, writer);
      writer.ldelim();
    }

    const spec = message.spec;
    if (spec !== null) {
      writer.uint32(18);
      writer.fork();
      PersistentVolumeSpec.encode(spec, writer);
      writer.ldelim();
    }

    const status = message.status;
    if (status !== null) {
      writer.uint32(26);
      writer.fork();
      PersistentVolumeStatus.encode(status, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PersistentVolume {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PersistentVolume();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          break;

        case 2:
          message.spec = PersistentVolumeSpec.decode(reader, reader.uint32());
          break;

        case 3:
          message.status = PersistentVolumeStatus.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metadata: ObjectMeta | null;
  spec: PersistentVolumeSpec | null;
  status: PersistentVolumeStatus | null;

  constructor(
    metadata: ObjectMeta | null = null,
    spec: PersistentVolumeSpec | null = null,
    status: PersistentVolumeStatus | null = null
  ) {
    this.metadata = metadata;
    this.spec = spec;
    this.status = status;
  }
}
