// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class PodAttachOptions {
  static encode(message: PodAttachOptions, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.stdin);

    writer.uint32(16);
    writer.bool(message.stdout);

    writer.uint32(24);
    writer.bool(message.stderr);

    writer.uint32(32);
    writer.bool(message.tty);

    writer.uint32(42);
    writer.string(message.container);
  }

  static decode(reader: Reader, length: i32): PodAttachOptions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PodAttachOptions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.stdin = reader.bool();
          break;

        case 2:
          message.stdout = reader.bool();
          break;

        case 3:
          message.stderr = reader.bool();
          break;

        case 4:
          message.tty = reader.bool();
          break;

        case 5:
          message.container = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  stdin: bool;
  stdout: bool;
  stderr: bool;
  tty: bool;
  container: string;

  constructor(
    stdin: bool = false,
    stdout: bool = false,
    stderr: bool = false,
    tty: bool = false,
    container: string = ""
  ) {
    this.stdin = stdin;
    this.stdout = stdout;
    this.stderr = stderr;
    this.tty = tty;
    this.container = container;
  }
}
