// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { OwnerReference } from "../../../apimachinery/pkg/apis/meta/v1/OwnerReference";

export class PodSignature {
  static encode(message: PodSignature, writer: Writer): void {
    const podController = message.podController;
    if (podController !== null) {
      writer.uint32(10);
      writer.fork();
      OwnerReference.encode(podController, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PodSignature {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PodSignature();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.podController = OwnerReference.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  podController: OwnerReference | null;

  constructor(podController: OwnerReference | null = null) {
    this.podController = podController;
  }
}
