// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectMeta } from "../../../apimachinery/pkg/apis/meta/v1/ObjectMeta";
import { PodTemplateSpec } from "./PodTemplateSpec";

export class PodTemplate {
  static encode(message: PodTemplate, writer: Writer): void {
    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectMeta.encode(metadata, writer);
      writer.ldelim();
    }

    const template = message.template;
    if (template !== null) {
      writer.uint32(18);
      writer.fork();
      PodTemplateSpec.encode(template, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PodTemplate {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PodTemplate();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          break;

        case 2:
          message.template = PodTemplateSpec.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metadata: ObjectMeta | null;
  template: PodTemplateSpec | null;

  constructor(
    metadata: ObjectMeta | null = null,
    template: PodTemplateSpec | null = null
  ) {
    this.metadata = metadata;
    this.template = template;
  }
}
