// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { NodeSelectorTerm } from "./NodeSelectorTerm";

export class PreferredSchedulingTerm {
  static encode(message: PreferredSchedulingTerm, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.weight);

    const preference = message.preference;
    if (preference !== null) {
      writer.uint32(18);
      writer.fork();
      NodeSelectorTerm.encode(preference, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PreferredSchedulingTerm {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PreferredSchedulingTerm();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.weight = reader.int32();
          break;

        case 2:
          message.preference = NodeSelectorTerm.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  weight: i32;
  preference: NodeSelectorTerm | null;

  constructor(weight: i32 = 0, preference: NodeSelectorTerm | null = null) {
    this.weight = weight;
    this.preference = preference;
  }
}
