// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ScopedResourceSelectorRequirement } from "./ScopedResourceSelectorRequirement";

export class ScopeSelector {
  static encode(message: ScopeSelector, writer: Writer): void {
    const matchExpressions = message.matchExpressions;
    for (let i: i32 = 0; i < matchExpressions.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ScopedResourceSelectorRequirement.encode(matchExpressions[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ScopeSelector {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ScopeSelector();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.matchExpressions.push(
            ScopedResourceSelectorRequirement.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  matchExpressions: Array<ScopedResourceSelectorRequirement>;

  constructor(matchExpressions: Array<ScopedResourceSelectorRequirement> = []) {
    this.matchExpressions = matchExpressions;
  }
}
