// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class SeccompProfile {
  static encode(message: SeccompProfile, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.type);

    writer.uint32(18);
    writer.string(message.localhostProfile);
  }

  static decode(reader: Reader, length: i32): SeccompProfile {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SeccompProfile();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.type = reader.string();
          break;

        case 2:
          message.localhostProfile = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  type: string;
  localhostProfile: string;

  constructor(type: string = "", localhostProfile: string = "") {
    this.type = type;
    this.localhostProfile = localhostProfile;
  }
}
