// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { ObjectMeta } from "../../../apimachinery/pkg/apis/meta/v1/ObjectMeta";

export class Secret {
  static encode(message: Secret, writer: Writer): void {
    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(10);
      writer.fork();
      ObjectMeta.encode(metadata, writer);
      writer.ldelim();
    }

    writer.uint32(40);
    writer.bool(message.immutable);

    const data = message.data;
    if (data !== null) {
      const dataKeys = data.keys();
      for (let i: i32 = 0; i < dataKeys.length; ++i) {
        const dataKey = dataKeys[i];
        writer.uint32(18);
        writer.fork();
        writer.uint32(10);
        writer.string(dataKey);
        writer.uint32(18);
        writer.bytes(data.get(dataKey));
        writer.ldelim();
      }
    }

    const stringData = message.stringData;
    if (stringData !== null) {
      const stringDataKeys = stringData.keys();
      for (let i: i32 = 0; i < stringDataKeys.length; ++i) {
        const stringDataKey = stringDataKeys[i];
        writer.uint32(34);
        writer.fork();
        writer.uint32(10);
        writer.string(stringDataKey);
        writer.uint32(18);
        writer.string(stringData.get(stringDataKey));
        writer.ldelim();
      }
    }

    writer.uint32(26);
    writer.string(message.type);
  }

  static decode(reader: Reader, length: i32): Secret {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Secret();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metadata = ObjectMeta.decode(reader, reader.uint32());
          break;

        case 5:
          message.immutable = reader.bool();
          break;

        case 2:
          let dataKey: string = "";
          let dataValue: Uint8Array = new Uint8Array(0);
          let dataHasKey: bool = false;
          let dataHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                dataKey = reader.string();
                dataHasKey = true;
                break;

              case 2:
                dataValue = reader.bytes();
                dataHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.data === null) {
              message.data = new Map<string, Uint8Array>();
            }
            const data = message.data;
            if (data !== null && dataHasKey && dataHasValue) {
              data.set(dataKey, dataValue);
            }
          }
          break;

        case 4:
          let stringDataKey: string = "";
          let stringDataValue: string = "";
          let stringDataHasKey: bool = false;
          let stringDataHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                stringDataKey = reader.string();
                stringDataHasKey = true;
                break;

              case 2:
                stringDataValue = reader.string();
                stringDataHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.stringData === null) {
              message.stringData = new Map<string, string>();
            }
            const stringData = message.stringData;
            if (stringData !== null && stringDataHasKey && stringDataHasValue) {
              stringData.set(stringDataKey, stringDataValue);
            }
          }
          break;

        case 3:
          message.type = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metadata: ObjectMeta | null;
  immutable: bool;
  data: Map<string, Uint8Array>;
  stringData: Map<string, string>;
  type: string;

  constructor(
    metadata: ObjectMeta | null = null,
    immutable: bool = false,
    data: Map<string, Uint8Array> = new Map(),
    stringData: Map<string, string> = new Map(),
    type: string = ""
  ) {
    this.metadata = metadata;
    this.immutable = immutable;
    this.data = data;
    this.stringData = stringData;
    this.type = type;
  }
}
