// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class TopologySelectorLabelRequirement {
  static encode(
    message: TopologySelectorLabelRequirement,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.key);

    const values = message.values;
    if (values.length !== 0) {
      for (let i: i32 = 0; i < values.length; ++i) {
        writer.uint32(18);
        writer.string(values[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): TopologySelectorLabelRequirement {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TopologySelectorLabelRequirement();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.key = reader.string();
          break;

        case 2:
          message.values.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  key: string;
  values: Array<string>;

  constructor(key: string = "", values: Array<string> = []) {
    this.key = key;
    this.values = values;
  }
}
