// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";
import { VolumeSource } from "./VolumeSource";

export class Volume {
  static encode(message: Volume, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    const volumeSource = message.volumeSource;
    if (volumeSource !== null) {
      writer.uint32(18);
      writer.fork();
      VolumeSource.encode(volumeSource, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Volume {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Volume();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.volumeSource = VolumeSource.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  volumeSource: VolumeSource | null;

  constructor(name: string = "", volumeSource: VolumeSource | null = null) {
    this.name = name;
    this.volumeSource = volumeSource;
  }
}
