# fly.toml file generated for suffiks-presentasjon on 2023-02-16T22:25:45+01:00

app          = "suffiks-presentasjon"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = [  ]

[env]

[experimental]
	auto_rollback = true

[[services]]
	http_checks   = [  ]
	internal_port = 8043
	processes     = [ "app" ]
	protocol      = "tcp"
	script_checks = [  ]

[[services.ports]]
	force_https = true
	handlers    = [ "http" ]
	port        = "80"
[[services.ports]]
	handlers = [ "tls", "http" ]
	port     = "443"
