controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.8.0
  manager:
    image:
      repository: ghcr.io/suffiks/suffiks
      tag: latest
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
  replicas: 1
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8091
    leaderElection:
      leaderElect: true
      resourceName: 0ff08fbf.suffiks.com
    metrics:
      bindAddress: 127.0.0.1:8090
    webhook:
      port: 9443
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
